first = {'Program': ['$', 'int', 'void'],
         'Declaration-list': ['int', 'void'],
         'Declaration': ['int', 'void'],
         'Declaration-initial': ['int', 'void'],
         'Declaration-prime': [';', '[', '('],
         'Var-declaration-prime': [';', '['],
         'Fun-declaration-prime': ['('],
         'Type-specifier': ['int', 'void'],
         'Params': ['int', 'void'],
         'Param-list-void-abtar': ['ID'],
         'Param-list': [','],
         'Param': ['int', 'void'],
         'Param-prime': ['['],
         'Compound-stmt': ['{'],
         'Statement-list': ['ID', ';', 'NUM', '(', '{', 'break', 'if', 'while', 'return', 'for', '+', '-'],
         'Statement': ['ID', ';', 'NUM', '(', '{', 'break', 'if', 'while', 'return', 'for', '+', '-'],
         'Expression-stmt': ['ID', ';', 'NUM', '(', 'break', '+', '-'],
         'Selection-stmt': ['if'],
         'Iteration-stmt': ['while'],
         'Return-stmt': ['return'],
         'Return-stmt-prime': ['ID', ';', 'NUM', '(', '+', '-'],
         'For-stmt': ['for'],
         'Vars': ['ID'],
         'Var-zegond': [','],
         'Var': ['ID'],
         'Expression': ['ID', 'NUM', '(', '+', '-'],
         'B': ['[', '(', '=', '<', '==', '+', '-', '*'],
         'H': ['=', '<', '==', '+', '-', '*'],
         'Simple-expression-prime': ['(', '<', '==', '+', '-', '*'],
         'Simple-expression-zegond': ['NUM', '(', '+', '-'],
         'C': ['<', '=='],
         'Relop': ['<', '=='],
         'Additive-expression': ['+', '-', '(', 'ID', 'NUM'],
         'Additive-expression-prime': ['+', '-', '*', '('],
         'Additive-expression-zegond': ['+', '-', '(', 'NUM'],
         'D': ['+', '-'],
         'Addop': ['+', '-'],
         'Term': ['+', '-', '(', 'ID', 'NUM'],
         'Term-prime': ['*', '('],
         'Term-zegond': ['+', '-', '(', 'NUM'],
         'G': ['*'],
         'Signed-factor': ['+', '-', '(', 'ID', 'NUM'],
         'Signed-factor-prime': ['('],
         'Signed-factor-zegond': ['+', '-', '(', 'NUM'],
         'Factor': ['(', 'ID', 'NUM'],
         'Var-call-prime': ['(', '['],
         'Var-prime': ['['],
         'Factor-prime': ['('],
         'Factor-zegond': ['(', 'NUM'],
         'Args': ['+', '-', '(', 'ID', 'NUM'],
         'Arg-list': ['+', '-', '(', 'ID', 'NUM'],
         'Arg-list-prime': [','],
         }

follow = {'Program': ['$', 'int', 'void'],
          'Declaration-list': ['int', 'void'],
          'Declaration': ['int', 'void'],
          'Declaration-initial': ['int', 'void'],
          'Declaration-prime': [';', '[', '('],
          'Var-declaration-prime': [';', '['],
          'Fun-declaration-prime': ['('],
          'Type-specifier': ['int', 'void'],
          'Params': ['int', 'void'],
          'Param-list-void-abtar': ['ID'],
          'Param-list': [','],
          'Param': ['int', 'void'],
          'Param-prime': ['['],
          'Compound-stmt': ['{'],
          'Statement-list': ['ID', ';', 'NUM', '(', '{', 'break', 'if', 'while', 'return', 'for', '+', '-'],
          'Statement': ['ID', ';', 'NUM', '(', '{', 'break', 'if', 'while', 'return', 'for', '+', '-'],
          'Expression-stmt': ['ID', ';', 'NUM', '(', 'break', '+', '-'],
          'Selection-stmt': ['if'],
          'Iteration-stmt': ['while'],
          'Return-stmt': ['return'],
          'Return-stmt-prime': ['ID', ';', 'NUM', '(', '+', '-'],
          'For-stmt': ['for'],
          'Vars': ['ID'],
          'Var-zegond': [','],
          'Var': ['ID'],
          'Expression': ['ID', 'NUM', '(', '+', '-'],
          'B': ['[', '(', '=', '<', '==', '+', '-', '*'],
          'H': ['=', '<', '==', '+', '-', '*'],
          'Simple-expression-prime': ['(', '<', '==', '+', '-', '*'],
          'Simple-expression-zegond': ['NUM', '(', '+', '-'],
          'C': ['<', '=='],
          'Relop': ['<', '=='],
          'Additive-expression': ['+', '-', '(', 'ID', 'NUM'],
          'Additive-expression-prime': ['+', '-', '*', '('],
          'Additive-expression-zegond': ['+', '-', '(', 'NUM'],
          'D': ['+', '-'],
          'Addop': ['+', '-'],
          'Term': ['+', '-', '(', 'ID', 'NUM'],
          'Term-prime': ['*', '('],
          'Term-zegond': ['+', '-', '(', 'NUM'],
          'G': ['*'],
          'Signed-factor': ['+', '-', '(', 'ID', 'NUM'],
          'Signed-factor-prime': ['('],
          'Signed-factor-zegond': ['+', '-', '(', 'NUM'],
          'Factor': ['(', 'ID', 'NUM'],
          'Var-call-prime': ['(', '['],
          'Var-prime': ['['],
          'Factor-prime': ['('],
          'Factor-zegond': ['(', 'NUM'],
          'Args': ['+', '-', '(', 'ID', 'NUM'],
          'Arg-list': ['+', '-', '(', 'ID', 'NUM'],
          'Arg-list-prime': [','],
          }
